### ISSUE TITLE
Repo's license

### ISSUE THREAD

**Issue by matthew1534** [nachocab/vscode-highlight-dodgy-characters#10]
Hi, this looks great. Is this repo under the MIT license or what is the license?

Very many thanks, Matthew

**Comment by nachocab** [comment]
Thanks, Matthew. It's the Do what you want license. 😁 I'm not updating it
anymore. Feel free to improve it.

**Comment by matthew1534** [comment]
Hi @nachocab , haha ok! 😂 Can I put a PR up to add a MIT licence so it's official that it can be used &/or forked off? Greatly, appreciated, just been battling some dodgy characters!!

**Comment by nachocab** [comment]
I just added it

**Comment by matthew1534** [comment]
thanks @nachocab :)
