### ISSUE TITLE
Version 1.0.0 on VS Code Marketplace

### ISSUE THREAD

**Issue by adamsmd** [nachocab/vscode-highlight-dodgy-characters#8]
The version listed on the marketplace (https://marketplace.visualstudio.com/items?itemName=nachocab.highlight-dodgy-characters) claims to be 1.0.0 but does not correspond to the current `master`.  As near as I can tell, it corresponds to commit c6f815 of this repository from Sep 10, 2017.

Could you update the version of the marketplace to use the latest version?  (I'd like to use the new features like the customizable whitelist.)

**Comment by waldyrious** [comment]
@nachocab any chance you could publish a new version off the current master? I would like to use this too, but the lack of a customizable whitelist is a deal-breaker :/

**Comment by gbuktenica** [comment]
@waldyrious I have a similar extension that has a customisable black list:
[Unicode Substitutions](https://github.com/gbuktenica/Unicode-Substitutions)
Not sure if this helps your use case.

**Comment by waldyrious** [comment]
Thanks for the heads-up, @gbuktenica. That extension seems to be about replacing characters, though, rather than highlighting them (which is what I need).

**Comment by gbuktenica** [comment]
Hi @waldyrious, the extension provides linting / highlighting as well as formatting / replacing. Also the replacing function can be disabled in the [user settings.](https://github.com/gbuktenica/Unicode-Substitutions/blob/master/README.md#disable-auto-document-formatting)

**Comment by waldyrious** [comment]
Thanks! I'll take a look then.
